In [7]:
import numpy as np
import os

In [8]:
for num in range(1,61):
    lines = [f.rstrip(". \n")+" " for f in open("./uniq_sent_60spkrs/x"+"{0:02}".format(num), "r").readlines()]
    os.system("mkdir spkr"+str(num))
    f = open("spkr"+str(num)+"/x"+"{0:03}".format(num)+".txt", "w")
    for line in lines:
        spaces = np.array([pos for pos, char in enumerate(line) if char == " "][0:]) # Find position of spaces.
        num_lines = int(max(spaces)/70)+1 # Estimate number of lines.
        breaks=[]
        for i in range(num_lines):
            breaks.append(max((spaces-70*(i+1))[(spaces-70*(i+1)) < 0])+70*(i+1)) # Estimate break positions.
        num_zeros = 7-num_lines
        front = int(num_zeros/2) # Empty lines before.
        back = num_zeros - front # Empty lines after.
        for i in range(front):
            f.write("\n")
        prev_break = 0
        for i in range(len(breaks)):
            print(line[prev_break:breaks[i]])
            f.write(line[prev_break:breaks[i]])
            f.write("\n")
            prev_break = breaks[i]+1
        for i in range(back):
            f.write("\n")
    f.close()

ಮರಳಿ ಮನೆಗೆ ಬಂದ ಮೇಲೆ ಅಪ್ಪ–ಅಮ್ಮನಿಗೂ ವಿಷಯ ಹೇಳಲಾರದೇ, ನಾನು ಅನುಭವಿಸಿದ ಒತ್ತಡ ನನ್ನನ್ನು ಹೈರಾಣ ಮಾಡಿತ್ತು 
[ 4 10 14 19 33 38 48 53 63 69 78 84 93]
[69, 93]
ಮರಳಿ ಮನೆಗೆ ಬಂದ ಮೇಲೆ ಅಪ್ಪ–ಅಮ್ಮನಿಗೂ ವಿಷಯ ಹೇಳಲಾರದೇ, ನಾನು ಅನುಭವಿಸಿದ ಒತ್ತಡ
ನನ್ನನ್ನು ಹೈರಾಣ ಮಾಡಿತ್ತು
ಈ ಅವಮಾನಗಳು, ದೈಹಿಕ ಹಾಗೂ ಮಾನಸಿಕ ಹಿಂಸೆಗಳನ್ನು ಅನುಭವಿಸುತ್ತಾ, ಜನರ ನಡುವೆ ಜೀವಿಸುವುದು ಹೇಗೆ? ಯಾವುದನ್ನು ಸ್ವೀಕರಿಸುವುದು ಯಾವುದನ್ನು ಬಿಡುವುದು ಎಂಬ ಗೊಂದಲ ಸೃಷ್ಟಿಯಾಗುತ್ತದೆ 
[  1  11  17  22  29  41  55  59  65  76  82  92 106 116 125 129 135 151]
[65, 135, 151]
ಈ ಅವಮಾನಗಳು, ದೈಹಿಕ ಹಾಗೂ ಮಾನಸಿಕ ಹಿಂಸೆಗಳನ್ನು ಅನುಭವಿಸುತ್ತಾ, ಜನರ ನಡುವೆ
ಜೀವಿಸುವುದು ಹೇಗೆ? ಯಾವುದನ್ನು ಸ್ವೀಕರಿಸುವುದು ಯಾವುದನ್ನು ಬಿಡುವುದು ಎಂಬ ಗೊಂದಲ
ಸೃಷ್ಟಿಯಾಗುತ್ತದೆ
ಕೊನೆಗೆ ಒಬ್ಬಳೇ ಇರುವಾಗ ಯಾಕೆ ಅವರು ನಮ್ಮನ್ನು ನೋಡಿ ನಕ್ಕರು, ಗೇಲಿ ಮಾಡಿದರು, ತಬ್ಬಿಕೊಂಡರು, ನಮ್ಮೊಟ್ಟಿಗೆ ನಿಲ್ಲಬೇಕಿದ್ದವರು ಯಾಕೆ ನಮ್ಮೊಂದಿಗೆ ನಿಂತಿಲ್ಲ – ಹೀಗೆ ಎಲ್ಲವನ್ನೂ ಯೋಚಿಸಿದ್ದೇನೆ 
[  6  13  20  25  30  39  44  52  57  66  79  91 107 112 123 132 134 139
 149 162]
[66, 139, 162]
ಕೊನೆಗೆ ಒಬ್ಬಳೇ ಇರುವಾಗ ಯಾಕೆ ಅವರು ನಮ್ಮನ್ನು ನೋಡಿ ನಕ್ಕರು, ಗೇಲಿ ಮಾಡಿದರು,
ತಬ್ಬಿಕೊಂಡರು, ನಮ್ಮೊಟ್ಟಿಗೆ ನಿಲ್ಲಬೇಕಿದ್ದವ

[ 5  9 17 22 30 41 46 57 64]
[64]
‘ಏಯ್, ತಾತ ಬಂದ್ರು. ಅತ್ತ ತಾತನಿಗೆ ಮೊಮ್ಮಕ್ಕಳು ನನಗೆ ಹೆದರಿದರೆಂಬ ತೃಪ್ತಿ
ಮೊಮ್ಮಕ್ಕಳಿಗೆ ತಾತನಿಂದ ಬೈಸಿಕೊಳ್ಳದೆ, ಅವರನ್ನು ಮಂಗ ಮಾಡಿದೆವು ಎಂಬ ಖುಷಿ 
[12 20 33 41 45 54 58 63]
[63]
ಮೊಮ್ಮಕ್ಕಳಿಗೆ ತಾತನಿಂದ ಬೈಸಿಕೊಳ್ಳದೆ, ಅವರನ್ನು ಮಂಗ ಮಾಡಿದೆವು ಎಂಬ ಖುಷಿ
ನನ್ನ ಸೂತ್ರದಲ್ಲಿ ಇಡಿ ಮನೆ ನಡೆಯುತ್ತಿದೆ ಎಂದು ಅಜ್ಜಿಗೆ ತೃಪ್ತಿ 
[ 4 15 19 23 35 40 48 55]
[55]
ನನ್ನ ಸೂತ್ರದಲ್ಲಿ ಇಡಿ ಮನೆ ನಡೆಯುತ್ತಿದೆ ಎಂದು ಅಜ್ಜಿಗೆ ತೃಪ್ತಿ
ಇಷ್ಟೆಲ್ಲವನ್ನೂ ಸಾಧ್ಯ ಮಾಡಿದ್ದು ಅಜ್ಜಿಯ ‘ಅನಲಿಟಿಕ’ ತಾನೆ? 
[13 19 28 35 45 51]
[51]
ಇಷ್ಟೆಲ್ಲವನ್ನೂ ಸಾಧ್ಯ ಮಾಡಿದ್ದು ಅಜ್ಜಿಯ ‘ಅನಲಿಟಿಕ’ ತಾನೆ?
ಊಟದ ವಿಚಾರದಲ್ಲಿಯೂ ಅಜ್ಜಿಯ ’ಅನಲಿಟಿಕ’ ಭರ್ಜರಿಯಾಗಿ ವರ್ಕೌಟ್ ಆಗುತ್ತದೆ 
[ 3 16 23 33 44 52 61]
[61]
ಊಟದ ವಿಚಾರದಲ್ಲಿಯೂ ಅಜ್ಜಿಯ ’ಅನಲಿಟಿಕ’ ಭರ್ಜರಿಯಾಗಿ ವರ್ಕೌಟ್ ಆಗುತ್ತದೆ
ಮನೆಯಲ್ಲಿ ಇರೋದು ಹತ್ತು ಜನರೇ ಆದರೂ ಎಲ್ಲರ ರುಚಿಯೂ ಭಿನ್ನ 
[ 8 14 20 25 30 36 43 49]
[49]
ಮನೆಯಲ್ಲಿ ಇರೋದು ಹತ್ತು ಜನರೇ ಆದರೂ ಎಲ್ಲರ ರುಚಿಯೂ ಭಿನ್ನ
ಒಂಬತ್ತು ಜನರಿಗೆ ಬೇಳೆಹೂರಣದ ಒಬ್ಬಟ್ಟು ಬೇಕು 
[ 7 14 24 33 38]
[38]
ಒಂಬತ್ತು ಜನರಿಗೆ ಬೇಳೆಹೂರಣದ ಒಬ್ಬಟ್ಟು ಬೇಕು
ಆದರೆ ಚಿಕ್ಕಪ್ಪನಿಗೆ ಮಾತ್ರ ಕಾಯಿಹೋಳಿಗೆ ಆಗಬೇಕು 
[ 4 17 23 34 41]
[41]
ಆದರೆ ಚಿಕ್ಕಪ್ಪನಿಗ

ಅವಳ ಆ ಸಂತೋಷದ ನಗೆ, ವಿಸ್ಮಯದ ಚಹರೆ, ಒಳಮನೆಯಿಂದ ಅಮ್ಮ ಬಂದು ಕರೆವಳೆಂಬ ತವಕದ ನಡುವೆ ನನ್ನನ್ನು ನನ್ನ ಬಾಲ್ಯಕ್ಕೆ ಕೊಂಡೊಯ್ಯಿತೆನ್ನ ವಿಚಾರ ಪ್ರಪಂಚ 
[  3   5  12  17  25  31  41  46  51  60  65  71  80  85  95 110 116 123]
[65, 123]
ಅವಳ ಆ ಸಂತೋಷದ ನಗೆ, ವಿಸ್ಮಯದ ಚಹರೆ, ಒಳಮನೆಯಿಂದ ಅಮ್ಮ ಬಂದು ಕರೆವಳೆಂಬ ತವಕದ
ನಡುವೆ ನನ್ನನ್ನು ನನ್ನ ಬಾಲ್ಯಕ್ಕೆ ಕೊಂಡೊಯ್ಯಿತೆನ್ನ ವಿಚಾರ ಪ್ರಪಂಚ
ಹುಡುಕಲೇ ಅವಳ ಮೊದಲ ಖುಷಿ, ನನ್ನ ಜೀವನಕ್ಕೆ ಹೋಲಿಸಿ? ಅಯ್ಯೋ ಪಾಪ! ಏನು ಹೇಳಬೇಕು ನನ್ನ ಮನಸ್ಸು? ಏಕೆಂದರೆ ಅದು ನೆನಪಿಟ್ಟುಕೊಂಡಿದೆಯಾ ನೆನಪಿಲ್ಲದ ನೆನಪಿನ ಆ ಎಳೆ ಬಾಲ್ಯದ ನೆನಹುಗಳನ್ನು? 
[  7  11  16  22  27  36  44  50  55  59  67  72  80  88  92 111 121 128
 130 134 141 154]
[67, 134, 154]
ಹುಡುಕಲೇ ಅವಳ ಮೊದಲ ಖುಷಿ, ನನ್ನ ಜೀವನಕ್ಕೆ ಹೋಲಿಸಿ? ಅಯ್ಯೋ ಪಾಪ! ಏನು ಹೇಳಬೇಕು
ನನ್ನ ಮನಸ್ಸು? ಏಕೆಂದರೆ ಅದು ನೆನಪಿಟ್ಟುಕೊಂಡಿದೆಯಾ ನೆನಪಿಲ್ಲದ ನೆನಪಿನ ಆ ಎಳೆ
ಬಾಲ್ಯದ ನೆನಹುಗಳನ್ನು?
ನನ್ನಷ್ಟಕ್ಕೆ ನಾನೇ ವಿಚಾರಲಹರಿಯಲ್ಲಿ ತೊಡಗಿ ಮುನ್ನಡೆದೆ ಒಲ್ಲದ ಮನಸ್ಸಿನಿಂದ, ತಕ್ಷಣವೇ ನೆನಪಾಯಿತು ಹಾಯಿಸಿದೆನೊಂದು ಕರೆ ಗೌಣತಂತ್ರದ ಮೂಲಕ 
[ 11  16  31  37  47  53  65  73  83  97 101 111 116]
[65, 116]
ನನ್ನಷ್ಟಕ್ಕೆ ನಾನೇ ವಿಚಾರಲಹರಿಯಲ್ಲಿ ತೊಡಗಿ ಮುನ್ನಡೆದೆ ಒಲ್ಲದ ಮನಸ್ಸಿನಿಂದ,
ತಕ

ಅಂದರೆ ಇವುಗಳ ಮೂಲವಾಗಿ ಗ್ರಹಗಳನ್ನೇ ಪತ್ತೆ ಮಾಡಿದಂತಾಯಿತು 
[ 5 11 19 30 36 49]
[49]
ಅಂದರೆ ಇವುಗಳ ಮೂಲವಾಗಿ ಗ್ರಹಗಳನ್ನೇ ಪತ್ತೆ ಮಾಡಿದಂತಾಯಿತು
ಹೀಗೆ ಒಂದು ಗ್ರಹವನ್ನು ಪತ್ತೆ ಮಾಡಿದರಷ್ಟೇ ಸಾಲದು 
[ 4  9 19 25 36 42]
[42]
ಹೀಗೆ ಒಂದು ಗ್ರಹವನ್ನು ಪತ್ತೆ ಮಾಡಿದರಷ್ಟೇ ಸಾಲದು
ಅದು ಎಷ್ಟು ದೂರದಲ್ಲಿದೆ? ಪರಿಭ್ರಮಣಾವಧಿ ಎಷ್ಟು ಎಂದೂ ಲೆಕ್ಕ ಹಾಕುವ ಉಪಾಯವನ್ನು ಡಾಪ್ಲರ್ ಪರಿಣಾಮ ಒದಗಿಸಿತು 
[ 3  9 21 34 40 45 51 57 67 75 82 91]
[67, 91]
ಅದು ಎಷ್ಟು ದೂರದಲ್ಲಿದೆ? ಪರಿಭ್ರಮಣಾವಧಿ ಎಷ್ಟು ಎಂದೂ ಲೆಕ್ಕ ಹಾಕುವ ಉಪಾಯವನ್ನು
ಡಾಪ್ಲರ್ ಪರಿಣಾಮ ಒದಗಿಸಿತು
ಒಂದು ಅವಧಿಯನ್ನು ಗುರುತಿಸಿದ ಮೇಲೆ ಅದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಇನ್ನೊಂದು ಅವಧಿಗಾಗಿ ಕಾಯಲೇಬೇಕಾಯಿತು 
[ 4 14 24 29 36 53 62 71 85]
[62, 85]
ಒಂದು ಅವಧಿಯನ್ನು ಗುರುತಿಸಿದ ಮೇಲೆ ಅದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ಇನ್ನೊಂದು
ಅವಧಿಗಾಗಿ ಕಾಯಲೇಬೇಕಾಯಿತು
ಆದರೆ ಈ ವಿಧಾನದ ಮುಖ್ಯ ಕೊರತೆಯೊಂದಿತ್ತು 
[ 4  6 13 19 34]
[34]
ಆದರೆ ಈ ವಿಧಾನದ ಮುಖ್ಯ ಕೊರತೆಯೊಂದಿತ್ತು
ಇದರಲ್ಲಿ ನಿಖರತೆ ಸಾಧಿಸಲಾಗಿರಲಿಲ್ಲ 
[ 7 14 30]
[30]
ಇದರಲ್ಲಿ ನಿಖರತೆ ಸಾಧಿಸಲಾಗಿರಲಿಲ್ಲ
ಅಲ್ಲದೆ ಗುರುಗ್ರಹದಂತಹ ದೊಡ್ಡ ದೊಡ್ಡ ಗ್ರಹಗಳನ್ನು ಮಾತ್ರ ಇದು ಗುರುತಿಸಿಕೊಟ್ಟಿತು 
[ 6 19 25 31 42 48 52 69]
[69]
ಅಲ್ಲದೆ ಗುರುಗ್ರಹದಂತಹ ದೊಡ್ಡ ದೊಡ್ಡ ಗ್ರಹಗಳನ್ನು ಮಾ

ಒಮ್ಮೆ ಅತಿಥಿಯಾಗಿದ್ದ ನನಗೂ ಈ ಮರ್ಯಾದೆ ಸಂದಿತು
ಹಾಗೆಂದು ಎಲ್ಲ ಸಾರು ಪೇಯ ಯೋಗ್ಯವಲ್ಲ. ಎಷ್ಟೋ ಸಾರು ಈ ಗೌರವದಿಂದ ವಂಚಿತವಾಗಿವೆ 
[ 7 12 17 21 32 38 43 45 54 66]
[66]
ಹಾಗೆಂದು ಎಲ್ಲ ಸಾರು ಪೇಯ ಯೋಗ್ಯವಲ್ಲ. ಎಷ್ಟೋ ಸಾರು ಈ ಗೌರವದಿಂದ ವಂಚಿತವಾಗಿವೆ
ಟೇಬಲ್ ಮೇಲೆ ಅಡುಗೆಯಿಟ್ಟುಕೊಂಡು ಶಿಸ್ತಾಗಿ ಕುಳಿತು ಉಣ್ಣುವ ಮನೆಯಿಂದ ಬಂದ ಬಾನುಗೆ, ಗಂಡಸರು ಊಟಕ್ಕೆ ಮೊದಲು ಕಾಫಿ– ಟೀಯಂತೆ ಸಾರು ಕುಡಿಯುವ ರಿವಾಜು ಅನಾಗರಿಕವಾಗಿ ಕಂಡಿತು 
[  5  10  27  36  43  50  58  62  70  77  84  90  96 103 108 116 123 135
 142]
[62, 135, 142]
ಟೇಬಲ್ ಮೇಲೆ ಅಡುಗೆಯಿಟ್ಟುಕೊಂಡು ಶಿಸ್ತಾಗಿ ಕುಳಿತು ಉಣ್ಣುವ ಮನೆಯಿಂದ ಬಂದ
ಬಾನುಗೆ, ಗಂಡಸರು ಊಟಕ್ಕೆ ಮೊದಲು ಕಾಫಿ– ಟೀಯಂತೆ ಸಾರು ಕುಡಿಯುವ ರಿವಾಜು ಅನಾಗರಿಕವಾಗಿ
ಕಂಡಿತು
ಆಘಾತದಿಂದ ಚೇತರಿಸಿಕೊಳ್ಳಲು ಅವಳಿಗೆಷ್ಟೊ ದಿನ ಹಿಡಿಯಿತು 
[ 8 23 34 38 47]
[47]
ಆಘಾತದಿಂದ ಚೇತರಿಸಿಕೊಳ್ಳಲು ಅವಳಿಗೆಷ್ಟೊ ದಿನ ಹಿಡಿಯಿತು
ಮೊದಮೊದಲು ಸಾರು ಕೊಡಲು ನಿರಾಕರಿಸಿದಳು 
[ 8 13 19 32]
[32]
ಮೊದಮೊದಲು ಸಾರು ಕೊಡಲು ನಿರಾಕರಿಸಿದಳು
ದಶ ದಿಕ್ಕುಗಳಿಗೂ ಮೊರೆಯಿಟ್ಟೆ. ಆಗ ನೆರವಿಗೆ ಧಾವಿಸಿದವರು ಅಕ್ಕಂದಿರು 
[ 2 14 26 29 37 48 58]
[58]
ದಶ ದಿಕ್ಕುಗಳಿಗೂ ಮೊರೆಯಿಟ್ಟೆ. ಆಗ ನೆರವಿಗೆ ಧಾವಿಸಿದವರು ಅಕ್ಕಂದಿರು
‘ಮುತ್ತಲ್ಲ ರತ್ನವಲ್ಲ, ಬರೇ ಸಾರು. ಅಷ್ಟೊಂದು ಓದಿ ನೌಕರಿ ಮಾಡುವ